<?php

namespace CompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchAnswerPropositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchAnswerPropositionRepository extends EntityRepository
{
}
